### ISSUE TITLE
Exceptions when loading the model

### ISSUE THREAD

**Issue by twmht** [ai-tor/VPilot#1] opened 2016-12-12 11:00 UTC
@ai-tor 

I installed keras and theano on windows 10.

But having exceptions when loading the model you give.

```
(deepDrive) C:\Users\GTA-01\VPilot>python drive.py model.json 8000 224 224
Using Theano backend.
Traceback (most recent call last):
  File "drive.py", line 55, in <module>
    model = model.getModel(model_path=args.model)
  File "C:\Users\GTA-01\VPilot\model.py", line 17, in getModel
    model = model_from_json(jfile.read())
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\models.py", line 197, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\utils\layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\models.py", line 996, in from_config
    layer = get_or_create_layer(first_layer)
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\models.py", line 980, in get_or_create_layer
    layer = layer_from_config(layer_data)
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\utils\layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "C:\Users\GTA-01\Anaconda3\envs\deepDrive\lib\site-packages\keras\layers\core.py", line 497, in from_config
    function = marshal.loads(config['function'].encode('raw_unicode_escape'))
AttributeError: 'list' object has no attribute 'encode'
```

I am not sure if this is the keras issue.

By the way, how do you train the model.json?

**Comment by aitorzip** [comment] 2016-12-12 11:04
Hi!

I think the problem is that my model was created with Keras in top of Tensorflow, not Theano. Also, it may happen that you are using Python 2 instead of Python 3.

I have not started training yet, for now VPilot is just a demonstration on how to use the RL model of DeepGTAV, probably in a month or so I will have code for training and also trained weights.

If you need code for training, I can share with you some examples that you can use. :)

**Comment by twmht** [comment] 2016-12-12 11:06
@ai-tor 

I am using python3.

So `model.json` is not the weight that you have trained?

then how it could be used for prediction?

**Comment by aitorzip** [comment] 2016-12-12 11:11
@twmht 

_model.json_ in fact is just the CNN architecture, the same there is in _model.py_ but with JSON format. The weights are actually in _model.h5_

_model.h5_ contains weights trained with [Udacity's dataset](https://github.com/udacity/self-driving-car/tree/master/challenges/challenge_2) so I don't expect those are going to work properly for GTAV. You will need to train them yourself or wait for me to do it :)

**Comment by twmht** [comment] 2016-12-12 11:17
@ai-tor 

So how do you generate `model.json`?

Maybe I can obtain that in the environment of keras and theano?

**Comment by aitorzip** [comment] 2016-12-12 12:12
Hi @twmht 

Keras has a method called _to_json()_ that generates the json string from any model, then you can use standard Python in/out functions to store that string into a file.

Here is an example taken from machinelearningmastery.com:

```
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")
```

**Comment by twmht** [comment] 2016-12-12 12:31
@ai-tor 

Big thanks! I will try it tomorrow.

By the way, Can you share some of example code for training?

**Comment by aitorzip** [comment] 2016-12-12 13:08
Yes! This afternoon I will send you some code :)

**Comment by twmht** [comment] 2016-12-12 13:11
@ai-tor 

Here is my email,  qrnnis2623891@gmail.com

Thank you :)

**Comment by aitorzip** [comment] 2016-12-12 13:19
Great! Talk to you by email later :)

**Comment by LemonAniLabs** [comment] 2016-12-13 08:52
Hi @ai-tor 
Same problem, do you have check the model.json encoding.
Cause there are many weird string in the file.
Just like....

>  {"config": [{"config": {"arguments": {}, "output_shape_type": "raw", "batch_input_shape": [null, 200, 66, 3], "input_dtype": "float32", "function": ["\u00e3\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0002\u0000\u0000\u0000S\u0000\u0000\u0000s\f\u0000\u0000\u0000|\u0000\u0000d\u0001\u0000\u001bd\u0002\u0000\u0018S)\u0003N\u00e7\u0000\u0000\u0000\u0000\u0000\u00e0_@\u00e7\u0000\u0000\u0000\u0000\u0000\u0000\u00f0?\u00a9\u0000)\u0001\u00da\u0001xr\u0003\u0000\u0000\u0000r\u0003\u0000\u0000\u0000\u00fa\bmodel.py\u00da\b<lambda>I\u0000\u0000\u0000s\u0000\u0000\u0000\u0000", null, null], "function_type": "lambda"


Any idea?
Thanks!!

**Comment by aitorzip** [comment] 2016-12-13 08:56
Wow! That's true, it looks like unicode....

Will check that in my machine this afternoon. Are you using Python 3 in Windows also?

To workaround this issue for now, you can just load the model without specifying the route, just doing `model.getModel()` and then load the weights manually with `model.load_weights("model.h5")`

**Comment by aitorzip** [comment] 2016-12-14 17:59
Hi guys,

I have been doing some tests in my laptop and everything is working fine on Windows 7 and Python 3.5.2 and Keras 1.1.2 on top of Tensorflow 0.12.

Can you check your versions and make sure that your Keras config is similar to this?

`{
    "backend": "tensorflow",
    "floatx": "float32",
    "image_dim_ordering": "tf",
    "epsilon": 1e-07
}`

Thanks!

**Comment by LemonAniLabs** [comment] 2016-12-15 04:06
My keras config is same to yours
```
{
    "image_dim_ordering": "tf",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}
```

Could you update the model.josn for unicode problem?
Or just give me the "function" value in model.json

`"input_dtype": "float32", "function":[HERE_NEED_YOUR_HELP], "function_type": "lambda"`

**Comment by aitorzip** [comment] 2016-12-15 09:27
Hi @LemonAniLabs ,

I have the same exact file in my computer and it works, so I guess this issue is machine dependent. So to solve this for once I deleted the json model and now it is loaded directly from the python script, so the issue with the json parsing is skipped and we make sure this doesn't happen again :)

Now, you take the weights file directly, like this:

> python drive.py model.h5 8000 200 66

**Comment by LemonAniLabs** [comment] 2016-12-15 12:53
Hi @ai-tor 
Thank you~ it's work!

**Comment by aitorzip** [comment] 2016-12-15 13:43
Great! I close the issue then :)

**Closed as completed** 2016-12-15 13:43 UTC

**Comment by monajalal** [comment] 2017-01-18 05:09
@ai-tor can you please share the training weights? Also the link didn't work
![screenshot from 2017-01-17 23-08-46](https://cloud.githubusercontent.com/assets/1892917/22051602/1099b7ba-dd0a-11e6-87b8-e72ecaa330f9.png)
